name: build_release

on:
  release:
    types:
      - created

jobs:
  createAndTestCRAFromNpm:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Create CRA from npm template
        run: npx create-react-app --template cra-template-rb .
      - run: npm run build
      - run: npm run test:generators
      - run: npm run lint
      - run: npm run checkTs
      - run: npm run cleanExampleApp
      - run: npm run build
      - run: npm run test:generators
      - run: npm run lint
      - run: npm run checkTs
